services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554/tcp"
      - "8888:8888/tcp"
      - "8889:8889/tcp"
      - "8890:8890/udp"
      - "8189:8189/udp"
      - "9997:9997/tcp"
      - "9998:9998/tcp"
    environment:
      - MTX_CONFIG=/mediamtx.yml
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro

  webui:
    image: nginx:alpine
    container_name: webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mediamtx
